"""The situation F042 was decided in, regenerated by running it."""

import pathlib
import sys
import tempfile

import numpy as np

CASE = pathlib.Path("data/case3_Llano/ert")


def invert(profile: int, regularization: dict, out: pathlib.Path) -> dict:
    """One resistivity inversion, with whatever regularization is handed in."""
    import pygimli as pg

    pg.rc["globalCache"] = False
    sys.path.insert(0, "scripts")
    sys.path.insert(0, "src")
    import case3_llano as case

    from ofag.plugins.protocol import PluginContext
    from ofag.plugins.pygimli_ert import PyGIMLiERTPlugin

    projects, record = case._project()
    state = case._load_state(projects.folder(record.project_id))
    item = next(i for i in state["ert_imports"] if i["profile"] == profile)
    spec = case._run_spec(record, item)
    physics = dict(spec.physics)
    physics["regularization"] = {**physics["regularization"], **regularization}
    result = PyGIMLiERTPlugin().execute(
        PluginContext(out), spec.model_copy(update={"physics": physics})
    )
    model = np.load(next(out.rglob("recovered_model.npy")))
    geometry = np.load(next(out.rglob("mesh_geometry.npz")))
    centres = geometry["cell_centers_m"]
    depth = 291.6 - centres[:, 1]
    band = (depth >= 5) & (depth < 15)
    # Restricted to the stretch the authors' number is read over.
    window = band & (centres[:, 0] >= 48) & (centres[:, 0] <= 76)
    return {
        "chi_squared": result.summary["chi_squared"],
        "band": float(np.median(model[band])),
        "window": float(np.median(model[window])),
        "window_max": float(model[window].max()),
    }


def main() -> None:
    print("A resistivity plugin inverts under an L2 model norm. The authors of this")
    print("release used robust L1 constraints instead, and a weathering front is the")
    print("kind of sharp boundary L2 cannot place, so the two norms were added.")
    print()
    print("What they do here, on the profile that does not fit:")
    print()
    root = pathlib.Path(tempfile.mkdtemp())
    print(
        f"   {'norm':22s} {'chi squared':>12s} {'whole line':>11s} {'x 48-76':>9s} {'its max':>9s}"
    )
    for label, regularization in (
        ("smooth, L2", {}),
        ("blocky, L1 on model", {"blocky_model": True}),
    ):
        got = invert(1, regularization, root / label.split(",")[0])
        print(
            f"   {label:22s} {got['chi_squared']:12.3f} "
            f"{got['band']:8.0f} ohm.m {got['window']:6.0f} ohm.m {got['window_max']:6.0f} ohm.m"
        )
    print()
    print("For comparison, the authors' own published section reads 912 ohm.m in that")
    print("band over x = 48 to 76 m, and this profile's misfit sits on the same stretch.")
    print()
    print("The capability is two boolean fields, about twenty-five lines, and is")
    print("exercised by one test. Nothing else in the project uses it.")


if __name__ == "__main__":
    main()
